// Copyright 2024 HACKSTONE
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

/* USB */
#define MANUFACTURER "YU"
#define PRODUCT "Yu75Pro"
#define VENDOR_ID 0xAA96
#define PRODUCT_ID 0xAA27
#define DEVICE_VER 0x0001

#define MD_BT1_NAME PRODUCT " BT1"
#define MD_BT2_NAME PRODUCT " BT2"
#define MD_BT3_NAME PRODUCT " BT3"
#define MD_BT4_NAME PRODUCT " BT4"
#define MD_BT5_NAME PRODUCT " BT5"
#define MD_DONGLE_PRODUCT PRODUCT " 2.4G"

#define LPWR_TIMEOUT (5 * 60000) // 无线休眠用时
#define WLS_KEYBOARD_REPORT_KEYS 5 // 无线模式默认按键无冲数量，最大是6

#define USB_SUSPEND_WAKEUP_DELAY 1000

#define USB_CABLE_PIN A15

/* UART */
#define UART_TX_PIN A9
#define UART_RX_PIN A10

/* SPI Config for spi flash*/
#define SPI_DRIVER SPIDM2
#define SPI_SCK_PIN C1
#define SPI_MOSI_PIN C3
#define SPI_MISO_PIN C2

#define EXTERNAL_FLASH_SPI_SLAVE_SELECT_PIN C0
#define WEAR_LEVELING_BACKING_SIZE (4 * 1024)
#define WEAR_LEVELING_LOGICAL_SIZE (WEAR_LEVELING_BACKING_SIZE / 2)

/* 存储数据比较多 */
#define WIRELESS_CONFIG_KB_SIZE 4 // 4个字节的设备信息
#define EECONFIG_KB_DATA_SIZE (WIRELESS_CONFIG_KB_SIZE)
#define WIRELESS_EECONFIG_ADDR (uint8_t *)(EECONFIG_KB_DATABLOCK)

/* COL2ROW or ROW2COL */
#define DIODE_DIRECTION COL2ROW
#define TAP_CODE_DELAY 10
#define DEBOUNCE 8
#define HOLD_ON_OTHER_KEY_PRESS

#define LPWR_DIODE_DIRECTION ROW2COL
#define LPWR_OUTPUT_STATE 1

#define LPWR_UART_WAKEUP_DISABLE
#define LPWR_WAK_MODE PAL_EVENT_MODE_RISING_EDGE

/* Key Matrix */
#define MATRIX_ROWS 6
#define MATRIX_COLS 16

#define MATRIX_ROW_PINS \
    { C9, C8, C7, C6, B15, B14 }
#define MATRIX_COL_PINS \
    { C11, C12, D2, B3, B4, B6, B7, A4, A5, A6, A7, C4, C5, B0, B1, B10 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
