VIA_ENABLE = yes

# 启用 LTO 优化（必须）
LTO_ENABLE = yes

# 禁用不必要的功能
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
NKRO_ENABLE = no
SLEEP_LED_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
TAP_DANCE_ENABLE = no

# 优化 RGB 矩阵
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes
